networks:
  streamwise-network:
    external: true

services:
  app:
    build:
      context: deployment
      dockerfile: Dockerfile
    container_name: streamwise-app
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - streamwise-network